name: Deploy Preview Documentation

on:
  pull_request:
    paths:
      - "docs/**"
      - "mkdocs.yaml"
      - ".github/workflows/deploy-preview-documentation.yml"

permissions:
  contents: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Generate cache ID
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Cache pip dependencies
        uses: actions/cache@v5
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Build documentation
        run: mkdocs build

      - name: Deploy to GitHub Pages (PR Preview)
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          destination_dir: preview/pr/${{ github.event.pull_request.number }}

      - name: Save PR metadata
        run: echo "${{ github.event.pull_request.number }}" > pr_number.txt

      - name: Upload PR metadata artifact
        uses: actions/upload-artifact@v7
        with:
          name: pr-metadata
          path: pr_number.txt

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v7
        with:
          name: documentation-preview-pr-${{ github.event.pull_request.number }}
          path: site/
          retention-days: 7
